samba_account:
  class: sfPropelRouteCollection
  options:
    model:               SambaAccount
    module:              samba_account
    prefix_path:         samba_account
    column:              id
    with_wildcard_routes: true

unix_account:
  class: sfPropelRouteCollection
  options:
    model:               UnixAccount
    module:              unix_account
    prefix_path:         unix_account
    column:              id
    with_wildcard_routes: true

email_alias:
  class: sfPropelRouteCollection
  options:
    model:               EmailAlias
    module:              emailalias
    prefix_path:         emailalias
    column:              id
    with_wildcard_routes: true

user_identification:
  class: sfPropelRouteCollection
  options:
    model:               UserIdentification
    module:              useridentification
    prefix_path:         useridentification
    column:              id
    with_wildcard_routes: true

user:
  class: sfPropelRouteCollection
  options:
    model:               User
    module:              user
    prefix_path:         user
    column:              id
    with_wildcard_routes: true

domainname:
  class: sfPropelRouteCollection
  options:
    model:               Domainname
    module:              domainname
    prefix_path:         domainname
    column:              id
    with_wildcard_routes: true

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
