comment:
  class: sfDoctrineRouteCollection
  options:
    model:               Comment
    module:              comment
    prefix_path:         comment
    column:              id
    with_wildcard_routes: true

change_language:
  url:   /change_language
  param: 
    module: language
    action: changeLanguage

ftp_account:
  class: sfDoctrineRouteCollection
  options:
    model:               FtpAccount
    module:              ftp_account
    prefix_path:         ftp_account
    column:              id
    with_wildcard_routes: true
    
samba_account:
  class: sfDoctrineRouteCollection
  options:
    model:               SambaAccount
    module:              samba_account
    prefix_path:         samba_account
    column:              id
    with_wildcard_routes: true
    
unix_account:
  class: sfDoctrineRouteCollection
  options:
    model:               UnixAccount
    module:              unix_account
    prefix_path:         unix_account
    column:              id
    with_wildcard_routes: true

email_alias:
  class: sfDoctrineRouteCollection
  options:
    model:               EmailAlias
    module:              emailalias
    prefix_path:         emailalias
    column:              id
    with_wildcard_routes: true

user_identification:
  class: sfDoctrineRouteCollection
  options:
    model:               UserIdentification
    module:              useridentification
    prefix_path:         useridentification
    column:              id
    with_wildcard_routes: true

user:
  class: sfDoctrineRouteCollection
  options:
    model:               User
    module:              user
    prefix_path:         user
    column:              id
    with_wildcard_routes: true


domainname:
  class: sfDoctrineRouteCollection
  options:
    model:               Domainname
    module:              domainname
    prefix_path:         domainname
    column:              id
    with_wildcard_routes: true


# default rules

default_homepage:
    url: /
    param: 
        module: user
        action: index

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
