generator:
  class: sfDoctrineGenerator
  param:
    model_class:           UserIdentification
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          user_identification
    with_doctrine_route:     1

    config:
      actions: ~
      fields:  
        user_id:
            label: User
      list:
        max_per_page: 5
        display: [identification, user_fullname]    
        title: User identification
      filter:  ~
      form:    ~
      edit:    
        title: Edit user Identification
      new:
        title: Add a new user Identification
