generator:
  class: sfPropelGenerator
  param:
    model_class:           Domainname
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          domainname
    with_propel_route:     1

    config:
      actions: ~
      fields:  
      list:    
        title: User Administration System
        batch_actions: {}
        display: [name, UserCount] 
        object_actions: {}
      filter:  
        class: false
      form:    ~
      edit:    ~
      new:     ~
